# html lang
# ---------------
language: en

# Main menu navigation
# ---------------
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about
  Java大纲: java.html
  #XXX: /xxx

# Favicon
# ---------------
favicon: /img/icon.ico

# PWA
# ---------------
pwa:
  enable: false
  manifest: 


# theme_color
theme_color:
  enable: true # or false -> to use the default theme
  main: "#000"
  paginator: "#000"
  button_hover: "#49B1F5"
  text_selection: "#000"
  link_color: "#000"
  hr_color: "#000"
  meta_color: "#000"

# Highlight theme
# ---------------
highlight_theme: default

# default,darker,pale night,light

# Nav settings
# ---------------
#social:
  #icon_name: url

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

# MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# Analysis
# ---------------
baidu_analytics: 

google_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
    #canvas-nest: /js/canvas-nest.js

# Post info settings
# ---------------
avatar: /img/avatar.png

top_img: /img/background.jpg # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

wordcount:
  enable: false

toc:
  enable: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# auto_excerpt:
#   enable: false
#   length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: true
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

sharejs:
  enable: true
  disabled_sites: google,facebook

# Comments System
# ---------------
disqus:
  enable: false 
  #shortname: 
  #count: 

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

gitalk:
  enable: true
  client_id: 8ee07b919a1bb5d250b7
  client_secret: 1d531cc27460532d4dd30ce696004408cc8052d2
  repo: 87828943.github.io
  owner: 87828943
  admin: 87828943

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is ture
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2018

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
links_title: Links
links:
  人生一世: 人生一世
  草木一秋: 草木一秋

# Follow Me
follow:
  enable: true
  url: 'tencent://message/?uin=81387949&amp;Menu=yes'
  text: 'Follow Me'

social:
  github: https://github.com/87828943
  weixin: 
  qq: tencent://message/?uin=81387949&amp;Menu=yes
  rss: /atom.xml